language: csharp
mono: none
dotnet: 2.0.3
dist: trusty

os:
  - linux
install:
  - export OS_KEY_NAME="$(lsb_release -c -s)"
  - sudo sh -c "echo deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$OS_KEY_NAME-prod $OS_KEY_NAME main > /etc/apt/sources.list.d/dotnetdev.list"
  - sudo apt-get update && sudo apt-get install dotnet-sdk-2.0.2 --allow-unauthenticated -y
script:
    - bash -c printenv | sort
    - dotnet --version
    - cd src 
    - dotnet restore
    - dotnet publish -c Release
    - cd bin/Release/netcoreapp2.0/publish 
    - dotnet Gallery.MVC.dll > my.log &
    - sleep 12
    - killall dotnet
    - cat my.log || true

    
  