runtime: aspnetcore
env: flex
env_variables:
  ASPNETCORE_URLS: 'http://*:5000'
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
network:
  forwarded_ports:
    - 80:5000
manual_scaling:
  instances: 1
