# about .net custom runtimes: https://cloud.google.com/appengine/docs/flexible/dotnet/customizing-the-dotnet-runtime
runtime: aspnetcore
env: flex
#  this way doesn't forward traffic by docker
#env_variables:
#  ASPNETCORE_URLS: 'http://0.0.0.0:5000'
resources:
  cpu: 1
  memory_gb: 0.8
  disk_size_gb: 10
network:
  forwarded_ports:
    - 80:5000
manual_scaling:
  instances: 1

# default: Intel(R) Xeon(R) CPU @ 2.30GHz, 2.3 GHz, 46080 KB Cache
# it seems this is for standard env
# instance_class: B1

